---
prompt_file: prompts/asqa_sum_or_ext.json
eval_file: data/asqa_eval_gtr_top100.json
shot: 2
ndoc: 10
dataset_name: asqa
tag: summary
model: llama-13b
temperature: 1.0
top_p: 0.95
use_shorter: summary
