---
prompt_file: prompts/asqa_light_inst.json
eval_file: data/asqa_eval_gtr_top100_reranked_oracle.json
shot: 2
ndoc: 3
dataset_name: asqa
tag: gtr_oracle_light_inst
model: llama-13b
temperature: 1.0
top_p: 0.95
