---
prompt_file: prompts/eli5_sum_or_ext.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 2
ndoc: 10
dataset_name: eli5
tag: extraction
model: llama-13b
temperature: 1.0
top_p: 0.95
use_shorter: extraction
