---
prompt_file: prompts/eli5_interact_doc_id.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 2
ndoc: 5
dataset_name: eli5
tag: bm25_interact_doc_id_extraction
model: gpt-3.5-turbo-0301
openai_api: true
use_shorter: extraction
interactive: true
interactive_query: doc_id
