---
prompt_file: prompts/qampari_sum_or_ext.json
eval_file: data/qampari_eval_gtr_top100.json
shot: 2
ndoc: 10
dataset_name: qampari
tag: summary
model: llama-13b
temperature: 1.0
top_p: 0.95
use_shorter: summary
