---
prompt_file: prompts/qampari_light_inst.json
eval_file: data/qampari_eval_gtr_top100_reranked_oracle.json
shot: 2
ndoc: 3
dataset_name: qampari
tag: gtr_oracle_light_inst
model: llama-13b
temperature: 1.0
top_p: 0.95
